"use client";

import { useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import "katex/dist/katex.min.css";
import { Check, Copy, Download, FileImage, FileText, Loader2 } from "lucide-react";

// ---------------------------------------------------------------
// Types + markdown builder
// ---------------------------------------------------------------

export interface PlanTopic {
    name: string;
    count: number;
}

export interface PlanDoc {
    title: string;
    subtitle?: string;
    totalQuestions: number;
    topics: PlanTopic[];                       // sorted desc by count
    blooms: PlanTopic[];                       // cognitive levels with counts
    highYield: string[];
    complex: string[];
    steps: { title: string; description: string }[];
    mockStrategy: { frequency?: string; coverage?: string; types?: string; review?: string };
    raw_text?: string;                         // backend fallback: unparsed markdown
}

const BLOOM_LEVELS = ["remember", "understand", "apply", "analyze", "evaluate", "create"];

function bloomLevel(name: string): number {
    const idx = BLOOM_LEVELS.indexOf(String(name).toLowerCase());
    return idx === -1 ? 0 : idx + 1;
}

const esc = (s: string) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ").trim();

export function buildPlanMarkdown(doc: PlanDoc): string {
    // Backend fallback: the LLM returned raw markdown (may already contain tables)
    if (doc.raw_text) {
        return doc.raw_text.trim();
    }

    const L: string[] = [];
    L.push(`# 🎯 Study Plan`);
    L.push("");
    L.push(`> **SENTINEL Intelligence Core**`);
    L.push(`> ${doc.title} · Based on **${doc.totalQuestions}** analyzed questions`);
    L.push("");

    if (doc.topics.length) {
        L.push("## High-Yield Topics");
        L.push("");
        L.push("| # | Topic | Questions | Priority |");
        L.push("|---|-------|-----------|----------|");
        doc.topics.slice(0, 8).forEach((t, i) => {
            const p = t.count >= 10 ? "🔴 High" : t.count >= 5 ? "🟠 Medium" : "🟢 Low";
            L.push(`| ${i + 1} | ${esc(t.name)} | ${t.count} | ${p} |`);
        });
        L.push("");
    }

    if (doc.blooms.length) {
        L.push("## Bloom's Taxonomy Focus");
        L.push("");
        L.push("| Level | Cognitive Level | Questions |");
        L.push("|-------|-----------------|-----------|");
        [...doc.blooms].sort((a, b) => b.count - a.count).forEach(b => {
            const lvl = bloomLevel(b.name);
            L.push(`| ${lvl ? `L${lvl}` : "—"} | ${esc(b.name)} | ${b.count} |`);
        });
        L.push("");
    }

    if (doc.complex.length) {
        L.push("## Complex Areas");
        L.push("");
        L.push("> **⚠ Spend extra time here**");
        doc.complex.forEach(c => L.push(`> - ${esc(c)}`));
        L.push("");
    }

    if (doc.steps.length) {
        L.push("## Action Steps");
        L.push("");
        L.push("| # | Step | Description |");
        L.push("|---|------|-------------|");
        doc.steps.forEach((s, i) => {
            L.push(`| ${i + 1} | ${esc(s.title)} | ${esc(s.description)} |`);
        });
        L.push("");
    }

    const strategy = doc.mockStrategy || {};
    if (Object.values(strategy).some(Boolean)) {
        L.push("## Mock Session Strategy");
        L.push("");
        L.push("| Aspect | Recommendation |");
        L.push("|--------|----------------|");
        if (strategy.frequency) L.push(`| Frequency | ${esc(strategy.frequency)} |`);
        if (strategy.coverage) L.push(`| Coverage | ${esc(strategy.coverage)} |`);
        if (strategy.types) L.push(`| Question Types | ${esc(strategy.types)} |`);
        if (strategy.review) L.push(`| Review | ${esc(strategy.review)} |`);
        L.push("");
    }

    L.push("---");
    L.push(`*Generated by SENTINEL Intelligence Core · ${new Date().toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" })}*`);
    return L.join("\n");
}

// ---------------------------------------------------------------
// Export helpers
// ---------------------------------------------------------------

function downloadUrl(url: string, filename: string) {
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
}

function downloadBlob(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    downloadUrl(url, filename);
    setTimeout(() => URL.revokeObjectURL(url), 2000);
}

type Html2Canvas = (
    el: HTMLElement,
    opts: { scale?: number; backgroundColor?: string | null; useCORS?: boolean; logging?: boolean }
) => Promise<HTMLCanvasElement>;

async function captureElement(el: HTMLElement, html2canvas: Html2Canvas): Promise<HTMLCanvasElement> {
    return html2canvas(el, {
        scale: 2,
        backgroundColor: null,
        useCORS: true,
        logging: false,
    });
}

// ---------------------------------------------------------------
// Component
// ---------------------------------------------------------------

interface StudyPlanMarkdownProps {
    doc: PlanDoc;
    className?: string;
    /** Renders the export toolbar (Copy / .md / PNG / PDF) */
    showExport?: boolean;
    exportPrefix?: string;
}

export function StudyPlanMarkdown({ doc, className, showExport = true, exportPrefix = "study-plan" }: StudyPlanMarkdownProps) {
    const markdown = buildPlanMarkdown(doc);
    const docRef = useRef<HTMLDivElement>(null);
    const [busy, setBusy] = useState<string | null>(null);
    const [copied, setCopied] = useState(false);

    const handleCopy = async () => {
        try {
            await navigator.clipboard.writeText(markdown);
            setCopied(true);
            setTimeout(() => setCopied(false), 1600);
        } catch {
            // Clipboard unavailable (e.g. non-secure context) — fall back to download
            downloadBlob(new Blob([markdown], { type: "text/markdown;charset=utf-8" }), `${exportPrefix}.md`);
        }
    };

    const handleDownloadMd = () => {
        downloadBlob(new Blob([markdown], { type: "text/markdown;charset=utf-8" }), `${exportPrefix}.md`);
    };

    const handlePng = async () => {
        if (!docRef.current || busy) return;
        setBusy("png");
        try {
            const { default: html2canvas } = await import("html2canvas");
            const canvas = await captureElement(docRef.current, html2canvas);
            downloadUrl(canvas.toDataURL("image/png"), `${exportPrefix}.png`);
        } finally {
            setBusy(null);
        }
    };

    const handlePdf = async () => {
        if (!docRef.current || busy) return;
        setBusy("pdf");
        try {
            const { default: html2canvas } = await import("html2canvas");
            const { jsPDF } = await import("jspdf");
            const canvas = await captureElement(docRef.current, html2canvas);
            const imgData = canvas.toDataURL("image/png");
            const pdf = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4", compress: true });
            const pageW = pdf.internal.pageSize.getWidth();
            const pageH = pdf.internal.pageSize.getHeight();
            const imgH = (canvas.height * pageW) / canvas.width;

            let heightLeft = imgH;
            let position = 0;
            pdf.addImage(imgData, "PNG", 0, position, pageW, imgH);
            heightLeft -= pageH;

            while (heightLeft > 0) {
                position -= pageH;
                pdf.addPage();
                pdf.addImage(imgData, "PNG", 0, position, pageW, imgH);
                heightLeft -= pageH;
            }
            pdf.save(`${exportPrefix}.pdf`);
        } finally {
            setBusy(null);
        }
    };

    return (
        <div className={className}>
            {showExport && (
                <div className="sticky top-0 z-20 mb-5 rounded-xl bg-[var(--nav-bg)] backdrop-blur-2xl border border-black/5 dark:border-white/10 px-3 py-2.5 shadow-lg shadow-black/5">
                <div className="grid grid-cols-2 sm:flex sm:flex-wrap items-center gap-2">
                    <button
                        onClick={handleCopy}
                        className="flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-lg text-[10px] font-black uppercase tracking-widest bg-emerald-500/10 border border-emerald-500/25 text-emerald-600 dark:text-emerald-400 hover:bg-emerald-500/20 active:scale-[0.97] transition-all"
                    >
                        {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                        {copied ? "Copied" : "Copy MD"}
                    </button>
                    <button
                        onClick={handleDownloadMd}
                        className="flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-lg text-[10px] font-black uppercase tracking-widest bg-emerald-500/10 border border-emerald-500/25 text-emerald-600 dark:text-emerald-400 hover:bg-emerald-500/20 active:scale-[0.97] transition-all"
                    >
                        <FileText className="w-3.5 h-3.5" /> .md
                    </button>
                    <button
                        onClick={handlePng}
                        disabled={busy !== null}
                        className="flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-lg text-[10px] font-black uppercase tracking-widest bg-indigo-500/10 border border-indigo-500/25 text-indigo-500 hover:bg-indigo-500/20 active:scale-[0.97] transition-all disabled:opacity-50"
                    >
                        {busy === "png" ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <FileImage className="w-3.5 h-3.5" />}
                        PNG
                    </button>
                    <button
                        onClick={handlePdf}
                        disabled={busy !== null}
                        className="flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-lg text-[10px] font-black uppercase tracking-widest bg-indigo-500/10 border border-indigo-500/25 text-indigo-500 hover:bg-indigo-500/20 active:scale-[0.97] transition-all disabled:opacity-50"
                    >
                        {busy === "pdf" ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
                        PDF
                    </button>
                    <span className="ml-auto hidden sm:block text-[9px] font-mono uppercase tracking-widest text-[var(--text-muted)]">
                        Markdown export
                    </span>
                </div>
                </div>
            )}

            {/* Captured element — solid bg so PNG/PDF exports look clean in both themes */}
            <div
                ref={docRef}
                className="bg-[#fbfbf8] dark:bg-[#141418] rounded-2xl border border-black/5 dark:border-white/10 p-6 md:p-10"
            >
                <div className="prose-sm md:prose max-w-none prose-slate dark:prose-invert prose-emerald prose-headings:font-black prose-headings:tracking-tight prose-blockquote:not-italic prose-table:text-xs prose-li:marker:text-emerald-500/70 prose-code:before:content-none prose-code:after:content-none prose-strong:text-[var(--text-primary)]">
                    <ReactMarkdown
                        remarkPlugins={[remarkGfm, remarkMath]}
                        rehypePlugins={[rehypeKatex]}
                        components={{
                            h1: ({ children }) => (
                                <h1 className="text-2xl md:text-3xl font-black italic tracking-tighter uppercase leading-tight text-[var(--text-primary)] mb-6 flex items-center gap-4">
                                    <span className="w-2 h-8 bg-emerald-500 rounded-full shrink-0" />
                                    {children}
                                </h1>
                            ),
                            h2: ({ children }) => (
                                <h2 className="text-base font-black uppercase tracking-widest text-[var(--text-primary)] mt-8 mb-4 flex items-center gap-3">
                                    {children}
                                    <span className="flex-1 h-px bg-emerald-500/25" />
                                </h2>
                            ),
                            h3: ({ children }) => (
                                <h3 className="text-sm font-black uppercase tracking-widest text-emerald-700 dark:text-emerald-300 mt-6 mb-3 flex items-center gap-2">
                                    <span className="w-1 h-3.5 bg-emerald-500/60 rounded-full" />
                                    {children}
                                </h3>
                            ),
                            p: ({ children }) => (
                                <p className="leading-relaxed text-[var(--text-primary)]">{children}</p>
                            ),
                            blockquote: ({ children }) => (
                                <blockquote className="my-4 px-4 py-3 rounded-lg border-l-4 border-emerald-500/50 bg-emerald-500/5 text-sm text-[var(--text-muted)]">
                                    {children}
                                </blockquote>
                            ),
                            code: ({ className, children }) => {
                                // Fenced blocks carry a `language-*` class, but plain ``` blocks don't —
                                // a newline inside `children` reliably means block code in markdown source.
                                const isBlock = /language-/.test(className ?? "") || String(children).includes("\n");
                                return isBlock ? (
                                    <code className={className}>{children}</code>
                                ) : (
                                    <code className="bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border border-emerald-500/15 rounded-md px-1.5 py-0.5 font-mono text-[0.85em]">
                                        {children}
                                    </code>
                                );
                            },
                            pre: ({ children }) => (
                                <pre className="!bg-[#101014] !text-slate-100 rounded-xl border border-black/10 dark:border-white/10 p-4 overflow-x-auto text-xs leading-relaxed !my-5">
                                    {children}
                                </pre>
                            ),
                            table: ({ children }) => (
                                <div className="my-5 overflow-x-auto rounded-lg border border-black/10 dark:border-white/10">
                                    <table className="w-full text-xs border-collapse">{children}</table>
                                </div>
                            ),
                            th: ({ children }) => (
                                <th className="px-3 py-2.5 text-left font-black uppercase tracking-widest text-[10px] bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border-b border-black/10 dark:border-white/10">
                                    {children}
                                </th>
                            ),
                            td: ({ children }) => (
                                <td className="px-3 py-2.5 align-top border-b border-black/5 dark:border-white/5 last:border-b-0">
                                    {children}
                                </td>
                            ),
                            ul: ({ children }) => (
                                <ul className="space-y-1.5 pl-5">{children}</ul>
                            ),
                            ol: ({ children }) => (
                                <ol className="space-y-1.5 pl-5">{children}</ol>
                            ),
                            hr: () => <hr className="my-8 border-black/10 dark:border-white/10" />,
                            a: ({ children, href }) => (
                                <a href={href} target="_blank" rel="noreferrer" className="text-emerald-600 dark:text-emerald-400 underline decoration-emerald-500/40 underline-offset-2 hover:decoration-emerald-500">
                                    {children}
                                </a>
                            ),
                        }}
                    >
                        {markdown}
                    </ReactMarkdown>
                </div>
            </div>
        </div>
    );
}
